### ISSUE TITLE
Associations with value being integer, not string, do not filter properly

### ISSUE THREAD

**Issue by mxgrn** [netzke/netzke-basepack#162]

**Comment by mxgrn** [comment]
Should be fixed in 4cdb2c1

**Comment by elitwin** [comment]
The in-grid filter now works properly with this commit. However, the Extended search screen (which I hadn't checked before) still sees it as a string field and shows "Contains" and "Matches" as the available operators rather than "Equals", "Greater than" and "Less than".

Also, when the association value is a 0, the grid still doesn't display the value until you double click on the cell.

In the image below, the first 9 rows all have Est. Hours set to 0, but they show as blank in the grid until you double click on a cell.

![image](https://cloud.githubusercontent.com/assets/85953/7069987/c7de2020-de90-11e4-94e5-79e30dd90a33.png)

**Comment by mxgrn** [comment]
Should now be fixed both in master and in 0-11.
